import type { DevelopmentCard } from "../types";

/**
 * Period 1 (1700-1749) development deck — 21 cards. Source: French fan
 * translation PDF supplied by the user (Champalaune Christophe), cross
 * checked against the English card art in the same file.
 */
export const DEVELOPMENT_CARDS_PERIOD_1: DevelopmentCard[] = [
  {
    id: "D1-01",
    number: 1,
    period: 1,
    titleEn: "Apache War",
    titleKo: "아파치 전쟁",
    flavorKo: "평원 아파치는 코만치의 공세를 당해내지 못한다...",
    timing: "while-in-play",
    apCost: null,
    effectKo:
      "플레이 중: 플레이어의 액션을 완료할 때마다, 어떤 부족에 황폐화(Ravaged) 카운터가 3개 이상 있으면 그 부족을 게임에서 제거하고 황폐화 카운터는 스톡으로 되돌린다.",
  },
  {
    id: "D1-02",
    number: 2,
    period: 1,
    titleEn: "Ute Alliance",
    titleKo: "우테족과의 동맹",
    flavorKo: "누믹어를 쓰는 사촌 부족들이 힘을 합친다...",
    timing: "play-from-hand",
    apCost: 1,
    effectKo:
      "1AP로 손에 든다. 손에서 플레이하여: 임의의 공간에 강도 3 밴드를 배치하거나, 주사위를 굴려 1-2면 효과 없음, 3-6이면 부족 또는 정착지 카운터 하나를 게임에서 제거한다(평화는 종료되지 않음).",
  },
  {
    id: "D1-03",
    number: 3,
    period: 1,
    titleEn: "War of Spanish Succession",
    titleKo: "에스파냐 왕위 계승 전쟁",
    flavorKo: "유럽의 전쟁이 신대륙에 혼란을 퍼뜨린다...",
    timing: "while-in-play",
    apCost: null,
    effectKo:
      "플레이 중: War와 Subjugate 지시(Instruction)는 효과가 없다. 적은 AP를 소비하지만, 그 절차가 플레이어에게 Recover 지시 실행을 강제하는 경우가 아니면 실제로 Instruction 절차를 실행하지 않는다.",
  },
  {
    id: "D1-04",
    number: 4,
    period: 1,
    titleEn: "Disease",
    titleKo: "질병",
    flavorKo: "유럽의 병원균이 코만치의 면역 체계를 무너뜨린다.",
    timing: "when-revealed",
    apCost: null,
    effectKo:
      "공개 시: 플레이 중인 란체리아 하나를 무작위로 선택해, 그 란체리아 자원 상자 내 모든 밴드의 강도를 1 줄인다. 이 카드는 버리고 대체 카드는 뽑지 않는다.",
  },
  {
    id: "D1-05",
    number: 5,
    period: 1,
    titleEn: "Missed Opportunity",
    titleKo: "놓친 기회",
    flavorKo: "코요테가 다시 한번 일을 저지른다...",
    timing: "when-revealed",
    apCost: null,
    effectKo: "공개 시: 플레이어 손에 있는 모든 개발 카드를 버려야 한다. 이 카드도 버리고 새 카드를 한 장 뽑는다.",
  },
  {
    id: "D1-06",
    number: 6,
    period: 1,
    titleEn: "Epidemic",
    titleKo: "역병",
    flavorKo: "역병이 모든 공동체를 휩쓴다.",
    timing: "when-revealed",
    apCost: null,
    effectKo:
      "공개 시: 각 영토마다 공간 하나를 무작위로 선택해 강도 -1(란체리아면 자원 상자의 모든 밴드가 영향받음), 부족 카운터가 있으면 제거한다. 플레이 중: 매 Take Actions 작전 종료 시, 지도에서 공간 하나를 무작위로 선택해 부족을 제거하거나 밴드 강도를 1 줄인다(밴드가 여럿이면 플레이어가 선택).",
  },
  {
    id: "D1-07",
    number: 7,
    period: 1,
    titleEn: "Spanish Trade Embargo",
    titleKo: "에스파냐의 통상 금지",
    flavorKo: "에스파냐 총독이 '야만 인디오'와의 교역을 금지한다.",
    timing: "while-in-play",
    apCost: null,
    effectKo: "플레이 중: 플레이어는 서쪽 적 공간이나 서쪽의 어떤 식민지 정착지에서도 교역(Trade)을 할 수 없다.",
  },
  {
    id: "D1-08",
    number: 8,
    period: 1,
    titleEn: "Mounted Society",
    titleKo: "기마 사회로의 전환",
    flavorKo: "코만치가 반보병 사회에서 완전한 기마 사회로 전환한다.",
    timing: "play-from-hand",
    apCost: 1,
    effectKo: "1AP로 손에 든다. 손에서 플레이하여 규칙 4.3 7단계에 따라 모든 란체리아를 이동시킬 수 있다.",
  },
  {
    id: "D1-09",
    number: 9,
    period: 1,
    titleEn: "Counting Coup",
    titleKo: "쿠 세기",
    flavorKo: "용맹한 코만치 전사들이 전투의 흐름을 바꾼다...",
    timing: "play-from-hand",
    apCost: 1,
    effectKo:
      "1AP로 손에 든다. 손에서 플레이하여 주사위 굴림이나 Success Check 드로우 하나를 무효화한다. 주사위를 다시 굴리거나, Success Check 카운터를 전부 컵에 되돌리고 다시 뽑는다.",
  },
  {
    id: "D1-10",
    number: 10,
    period: 1,
    titleEn: "Prominent Headman",
    titleKo: "영향력 있는 지도자",
    flavorKo: "에쿠아라카파 부족은 군사적 업적에서 견줄 자가 없었다...",
    timing: "play-from-hand",
    apCost: 1,
    effectKo:
      "1AP로 손에 든다. Passage of Time 중 파라이보/마히미아나의 Headman Death Check 대신 손에서 플레이한다 — 해당 헤드맨은 죽지 않는다.",
  },
  {
    id: "D1-11",
    number: 11,
    period: 1,
    titleEn: "Siege of Jicarilla",
    titleKo: "히카리야 포위전",
    flavorKo: "아파치 마을에 대한 코만치의 공격이 9일간의 전투로 정점에 이른다...",
    timing: "play-from-hand",
    apCost: 1,
    effectKo: "1AP로 손에 든다. 손에서 플레이하여 임의의 한 부족에 황폐화 카운터 2개, 혹은 두 부족에 각각 1개씩 배치한다.",
  },
  {
    id: "D1-12",
    number: 12,
    period: 1,
    titleEn: "Great Hunt",
    titleKo: "대규모 사냥",
    flavorKo: "대규모 들소 떼가 목격되었다...",
    timing: "play-from-hand",
    apCost: 1,
    effectKo: "1AP로 손에 든다. 밴드 활성화 중 손에서 플레이하면, 이번 밴드 활성화 동안 Hunt 액션 비용이 1MP로 줄어든다.",
  },
  {
    id: "D1-13",
    number: 13,
    period: 1,
    titleEn: "French Traders",
    titleKo: "프랑스 상인들",
    flavorKo: "프랑스 상인들이 루이지애나에서 강을 거슬러 올라온다...",
    timing: "play-from-hand",
    apCost: 1,
    effectKo:
      "1AP로 손에 든다. Take Actions 중 손에서 플레이하여, Lower Arkansas/Red River/Brazos Colorado 영토의 비어있는 원형 공간에서 AP 비용 없이 Trade 액션을 수행한다. 최대 Bison/Horses 2개를 같은 수의 Guns로 교환할 수 있다.",
  },
  {
    id: "D1-14",
    number: 14,
    period: 1,
    titleEn: "Disease",
    titleKo: "질병 (2)",
    flavorKo: "유럽의 병원균이 코만치의 면역 체계를 무너뜨린다.",
    timing: "when-revealed",
    apCost: null,
    effectKo:
      "공개 시: 플레이 중인 란체리아 하나를 무작위로 선택해, 그 란체리아 자원 상자 내 모든 밴드의 강도를 1 줄인다. 이 카드는 버리고 대체 카드는 뽑지 않는다.",
  },
  {
    id: "D1-15",
    number: 15,
    period: 1,
    titleEn: "Negotiation",
    titleKo: "협상",
    flavorKo: "능숙한 외교로 분쟁이 끝난다...",
    timing: "play-from-hand",
    apCost: 1,
    effectKo:
      "1AP로 손에 든다. Planning 작전 중 손에서 플레이(Headman Action, 4단계 중에도 사용 가능): 플레이 중인 War Column 하나를 선택하면 그 전쟁이 종료된다.",
  },
  {
    id: "D1-16",
    number: 16,
    period: 1,
    titleEn: "Quality Mounts",
    titleKo: "우수한 말",
    flavorKo: "코만치의 조랑말은 전설적인 자질을 지녔다...",
    timing: "play-from-hand",
    apCost: 1,
    effectKo:
      "1AP로 손에 든다. 손에 있는 동안: 밴드 활성화 시 MP 보너스를 최대 6까지 사용할 수 있다(카드를 잃을 위험 감수). 밴드 활동 종료 후 주사위를 굴려, 사용한 보너스 MP 이하가 나오면 이 카드를 버린다.",
  },
  {
    id: "D1-17",
    number: 17,
    period: 1,
    titleEn: "Tactical Advantage",
    titleKo: "전술적 우위",
    flavorKo: "적들은 코만치의 전술을 당해내지 못한다...",
    timing: "play-from-hand",
    apCost: 1,
    effectKo:
      "1AP로 손에 든다. 손에 있는 동안, Success Check 1단계에서 이 카드를 잃을 위험을 감수하고 우위를 노릴 수 있다: 주사위 굴림 1-2=카드 버림, 3-4=Success 1개 뽑은 것으로 처리(의약 영향 없음), 5-6=Success 1개로 처리하고 뽑힌 Enemy AP 카운터 1개를 무작위로 드로우 컵에 되돌린다.",
  },
  {
    id: "D1-18",
    number: 18,
    period: 1,
    titleEn: "No Relief From War",
    titleKo: "전쟁에 자비란 없다",
    flavorKo: "코만치의 공세는 가차없다...",
    timing: "play-from-hand",
    apCost: 1,
    effectKo:
      "1AP로 손에 든다. 적의 Recover 지시가 실행될 때, 주사위를 굴리기 전에 손에서 플레이한다: Enemy AP는 지시 실행에 소비되지만 황폐화 카운터는 제거되지 않는다.",
  },
  {
    id: "D1-19",
    number: 19,
    period: 1,
    titleEn: "End of Ute Alliance",
    titleKo: "우테 동맹의 종말",
    flavorKo: "우테-코만치 연합이 붕괴한다...",
    timing: "when-revealed",
    apCost: null,
    effectKo:
      "공개 시: Upper Arkansas #1에 사용 가능한 부족 카운터를 배치한다. 그 공간의 Bison은 제거하고, 그 공간의 란체리아는 Upper Arkansas 내 적재 한도 내 다른 공간으로 옮긴다(옮길 곳이 없으면 란체리아 파괴). 플레이 중: Upper Arkansas #1의 부족은 Upper Arkansas의 코만치 통제 판정에 포함되지 않는다.",
  },
  {
    id: "D1-20",
    number: 20,
    period: 1,
    titleEn: "Taos Pueblo Trade Opened to Comanches",
    titleKo: "타오스 푸에블로 교역 개방",
    flavorKo: "타오스 푸에블로는 미국 남서부 원주민들의 주요 교역 중심지였다...",
    timing: "while-in-play",
    apCost: null,
    effectKo:
      "플레이 중: 서쪽 적 사각 공간만 교역 목적으로는 평화 공간으로 취급한다. 다만 그 공간에서 Raid나 전쟁 행동은 할 수 없다.",
  },
  {
    id: "D1-21",
    number: 21,
    period: 1,
    titleEn: "Mild Winter",
    titleKo: "온화한 겨울",
    flavorKo: "남부 평원의 온화한 겨울이 들소 떼를 끌어들인다...",
    timing: "when-revealed",
    apCost: null,
    effectKo: "공개 시: Passage of Time 절차의 12단계를 수행한다.",
  },
];
